[phases.setup]
  nixPkgs = ["nginx"]

[phases.build]
  cmds = ["mkdir -p dist && cp -r assets files index.html script.js style.css file-modal.css doom-code.jpg doom.png CNAME dist/"]

[static]
  directory = "dist"
